### ISSUE TITLE
Pig Spawner?

### ISSUE THREAD

**Issue by EmanuelSimard** [TheBusyBiscuit/Slimefun5#41]
## Description
So my players finally got a broken blaze spawner and repaired it. Only got a pig spawner. Is this normal?
## Screenshots (if available)
<img width="572" alt="screen shot 2018-08-30 at 10 13 42 pm" src="https://user-images.githubusercontent.com/26827533/44889073-5b39e380-aca2-11e8-8077-0491522a8603.png">

## Build / Version (if available)
**Slimefun4-52.jar**

**Comment by TheBusyBiscuit** [comment]
Wrong project.
Go to Slimefun4's repo.
